function [In] = create_Input_fct(dir_save,mode, path_to_disch_mat, disch_mat ,f, beta, r, IP, save_input, Spe, Rea, Precal, disch, Para)

if ~exist('IP','var') || ~isstruct(IP)
    IP = struct();
end
% Loading data to feed into the solver
% This part loads and renames a lot of info saved in "structures" that were
% pre-generated by other files in their directories' folder.
% - Names of the files we choose to lunch the input

% FIXME MERGE
% NOTE : This is a bit of a hacky fix
avail_disch_types = {'ArTi', 'ArW', 'ArCu', 'ArC', 'ArCr', 'ArAl', 'ArZr', 'ArN2Ti', 'N2Ti', 'ArMo', 'HeMo','ArNeC', 'ArSi'};
if isfield(IP,'disch_type') && any(strcmpi(avail_disch_types,IP.disch_type))
    type = IP.disch_type;
elseif isfield(mode,'disch_type') && any(strcmpi(avail_disch_types,mode.disch_type))
    type = mode.disch_type;
else
    warning('No valid discharge type supplied. Using ArCu as default.');
    type = 'ArCu';
end

% TODO : dissalow loading variables from files here and only allow passing
% as arguments
if ~exist('Spe','var') || ~exist('Rea','var') || ~exist('Precal','var') ||  ~exist('disch','var') || ~exist('Para','var')
    [Spe, Rea, Precal, disch, Para] = import_data(path_to_disch_mat,disch_mat,type);
end

if ~isfield(disch,'U')
    % FIXME: should be handled further up
    % NOTE: this is just for compatibility
    disch.U = disch.V;
    disch = rmfield(disch,'V');
end
if mean(disch.U) > 0
    disch.U = -disch.U;
    % FIXME: really shouldn't be necessary
    % NOTE: Further down the line we use the absolute value anyway
end

% TODO : add additional checks and warnings/corrections for the disch
% structure:
% 1. warn if arrays are too long (suggest subsampling)
% 2. warn and correct disch.dt and disch.T if they're in units of seconds
% instead of microseconds
% 3. warn if discharge type is not specified
% 4. suggest specifiyng pressure and measured F_flux if not provided
% NOTE : these checks and fixes belong in a seperate function and should be
% handled further up

 %% Defining or temperarily changing some quantities here
% Defining
Names = Spe.Names ; % Names are short names for each species in order.
List = Spe.List;
s = Spe.s ; % ordering number of species: "s.Names". Ex: s.e is 1, s.Ti is 8
Tec = length(Names)+1  ; % ordering number of T_ec, just a number, interger.

%% Ranges
%group the sepecies into ranges that represent certain qualities

% FIXME MERGE
% NOTE : this information should already specified in Spe_xy.mat
% TODO : FIX THIS ^
switch lower(type)
    case 'arti'
        % find(Spe.Q ~= 0 & ~strcmp(Spe.PSpecies, 'e'))
        Range.ion =         [s.Ari s.Arii s.Tii s.Tiii];7
        Range.refill =      [s.Ar];
        Range.meta =        [s.Arm3P0 s.Arm3P2];
        Range.sput_metal =  [s.Ti];
        Range.sput_gas =    [s.ArW s.ArH];
        Range.kickout =     [s.Ar s.Arm3P0 s.Arm3P2];
    case 'arw'
        Range.ion =         [s.Ari s.Arii s.Wi s.Wii];
        Range.refill =      [s.Ar];
        Range.meta =        [s.Arm3P0 s.Arm3P2];
        Range.sput_metal =  [s.W];
        Range.sput_gas =    [s.ArW s.ArH];
        Range.kickout =     [s.Ar s.Arm3P0 s.Arm3P2];
    case 'arcu'
        Range.ion =         [s.Ari s.Arii s.Cui s.Cuii];
        Range.refill =      [s.Ar];
        Range.meta =        [s.Arm3P0 s.Arm3P2];
        Range.sput_metal =  [s.Cu s.Cum1 s.Cum2 s.Cum3];
        Range.sput_gas =    [s.ArW s.ArH];
        Range.kickout =     [s.Ar s.Arm3P0 s.Arm3P2];
    case 'arc'
        Range.ion =         [s.Ari s.Arii s.Ci s.Cii];
        Range.refill =      [s.Ar];
        Range.meta =        [s.Arm3P0 s.Arm3P2];
        Range.sput_metal =  [s.C s.Cm1 s.Cm2 s.Cm3];
        Range.sput_gas =    [s.ArW s.ArH];
        Range.kickout =     [s.Ar s.Arm3P0 s.Arm3P2];
    case 'aral'
        Range.ion =         [s.Ari s.Ali s.Alii];
        Range.refill =      [s.Ar];
        Range.meta =        [s.Arm3P0:s.Arm3P2];
        Range.sput_metal =  [s.Al];
        Range.sput_gas =    [s.ArW s.ArH];   
        Range.kickout =     [s.Ar s.Arm3P0 s.Arm3P2];
    case 'arzr'
        Range.ion =         [s.Ari s.Arii s.Zri s.Zrii];
        Range.refill =      [s.Ar];
        Range.meta =        [s.Arm3P0:s.Arm3P2];
        Range.sput_metal =  [s.Zr];
        Range.sput_gas =    [s.ArW s.ArH];
        Range.kickout =     [s.Ar s.Arm3P0 s.Arm3P2];
    case 'arcr'
        Range.ion =         [s.Ari s.Arii s.Cri s.Crii];
        Range.refill =      [s.Ar];
        Range.meta =        [s.Arm3P0:s.Arm3P2];
        Range.sput_metal =  [s.Cr];
        Range.sput_gas =    [s.ArW s.ArH];
        Range.kickout =     [s.Ar s.Arm3P0 s.Arm3P2];
    case 'n2ti'
        Range.ion =         [s.Ni s.N2i s.Tii s.Tiii]; % s.N3i s.N4i
        Range.refill =      [s.N2];
        Range.meta =        [s.N2A s.ND s.NP s.NS];
        Range.sput_metal =  [s.Ti];
        Range.sput_gas =    [];
        Range.kickout =     [];
        Range.kickout_r =   [s.N2 s.N2A s.NS s.ND s.NP];
        % NOTE N2 : we're ignoring this for the moment until we figure out
        % how to handle kickout properly (especially with multiple species)
        mode.reactive = true;
    case 'arn2ti'
        Range.ion =         [s.Ari s.Arii s.Ni s.N2i s.Tii s.Tiii]; % s.N3i s.N4i
        Range.refill =      [s.Ar s.N2];
        Range.meta =        [s.Arm3P0 s.Arm3P2 s.N2A s.ND s.NP s.NS];
        Range.sput_metal =  [s.Ti];
        Range.sput_gas =    [s.ArW s.ArH];
        Range.kickout =     [s.Ar s.Arm3P0 s.Arm3P2];
        Range.kickout_r =   [s.N2 s.N2A s.NS s.ND s.NP];
        % NOTE N2 : we're ignoring this for the moment until we figure out
        % how to handle kickout properly (especially with multiple species)
        mode.reactive = true;
    case 'armo'
        Range.ion =         [s.Ari s.Arii s.Moi s.Moii];
        Range.refill =      [s.Ar];
        Range.meta =        [s.Arm3P0 s.Arm3P2];
        Range.sput_metal =  [s.Mo];
        Range.sput_gas =    [s.ArW s.ArH];
        Range.kickout =     [s.Ar s.Arm3P0 s.Arm3P2];
    case 'hemo'
        Range.ion =         [s.Hei s.Moi s.Moii];
        Range.refill =      [s.He];
        Range.meta =        [s.Hem2S1];
        Range.sput_metal =  [s.Mo];
        Range.sput_gas =    [s.HeW s.HeH];
        Range.kickout =     [s.He s.Hem2S0 s.Hem2S1 s.He2P012 s.He2P1]; % TODO : @Zakaria I added the other neutral He species except HeW and HeH - please revert if this they were intentionally left out /joel
    case 'arnec'
        Range.ion =         [s.Ari s.Arii s.Nei s.Neii s.Ci s.Cii];
        Range.refill =      [s.Ar s.Ne];
        Range.meta =        [s.Arm3P0 s.Arm3P2 s.Nem2P0 s.Nem2P2];
        Range.sput_metal =  [s.C];
        Range.sput_gas =    [s.ArW s.ArH s.NeW s.NeH];
        Range.kickout =     [s.Ar s.Arm3P0 s.Arm3P2 s.Ne s.Nem2P0 s.Nem2P2];  %?? kicked species
    case 'arsi'
        Range.ion =         [s.Ari s.Arii s.Sii s.Siii];
        Range.refill =      [s.Ar];
        Range.meta =        [s.Arm3P0:s.Arm3P2];
        Range.sput_metal =  [s.Si];
        Range.sput_gas =    [s.ArW s.ArH];
        Range.kickout =     [s.Ar s.Arm3P0 s.Arm3P2];

end

% Temporarily changing some values
T_e0 = 0.5; % initial value of the electron temperature

% FIXME
if ~isfield(IP,'pressure')
    %error("No pressure supplied");
    warning("No pressure specified. Using default default pressure (0.5Pa).");
    Pressure = 0.5; % in Pa
else
    Pressure = IP.pressure;
end

% Fitting parameter values in single run
Para.f = f;
Para.beta = beta;
Para.r = r;
% MRu: included 2020-02-18 for IRM v1.2

% FIXME
if isfield(IP, 'pulseLength')
    Para.pulseLength = IP.pulseLength;
else
    if ~isfield(disch, 't_pulse_end')
        U_thresh = 200;
        ind = find(abs(disch.U(end:-1:1)) > U_thresh,1, 'first');
        disch.t_pulse_end = disch.T(end-ind);
    end
    Para.pulseLength = disch.t_pulse_end;
end

Para.varf = 0; % if varf = 1 -> use variable f option (see Brenning: "The link between B field strength ..."
% only necessary if var f is selected
Para.Bfield = 0.03; % 
%Para.deg_poi = deg_poi;
Para.hall = 8.5; % not important, will be fitted 

%% Recalculate some values
% FIXME : this is currently Ar specific
% due to the temperary adjuestment of values, some values are recalculated

if contains('Ar', Spe.Refill_gases)
    if isfield(IP,'pp_Ar')
        pp_Ar = IP.pp_Ar;
    else
        pp_Ar = IP.pressure;
    end
    Spe.ID(s.Ar) = Spe.ID(s.Ar)*pp_Ar;

    % the change of pressure modified above changes the intial density of Ar
    % this is inconsitent to the 500
    % K (0.0431 eV) found in
    % species_reactions/create_species_new.m
    % Spe.ID(s.e) = dot(Spe.Q(2:end), Spe.ID(2:end)); % quasi-neutrality
end
if contains('Ne', Spe.Refill_gases)
    if isfield(IP,'pp_Ne')
        pp_Ne = IP.pp_Ne;
    else
        pp_Ne = IP.pressure;
    end
    Spe.ID(s.Ne) = Spe.ID(s.Ne)*pp_Ne;
    Spe.ID(s.Nei) = Spe.ID(s.Nei)*pp_Ne;
    % the change of pressure modified above changes the intial density of Ar
    % this is inconsitent to the 500
    % K (0.0431 eV) found in
    % species_reactions/create_species_new.m
    % Spe.ID(s.e) = dot(Spe.Q(2:end), Spe.ID(2:end)); % quasi-neutrality
end

if contains('N2', Spe.Refill_gases)
    if isfield(IP,'pp_N2')
        pp_N2 = IP.pp_N2;
    else
        pp_N2 = IP.pressure;
    end
    Spe.ID(s.N2) = Spe.ID(s.N2)*pp_N2;
end
if contains('He', Spe.Refill_gases)
    if isfield(IP,'pp_He')
        pp_He = IP.pp_He;
    else
        pp_He = IP.pressure;
    end
    Spe.ID(s.He) = Spe.ID(s.He)*pp_He;
end

Spe.ID(s.e) = dot(Spe.Q(2:end), Spe.ID(2:end)); % quasi-neutrality
% NOTE : HeMo currently relies on having way too many electrons at the start
% NOTE : During integration, it is assured that the total charge is
% conserved, so if quasi-neutrality doesn't hold in the begining, it won't
% hold throught the entire simulation

if size(Spe.ID, 2) ~= 1; Spe.ID = Spe.ID.'; end % FIXME : this should be done in the species creation 

Spe.B(Range.ion) = Para.beta; % assign the same beta to all ions
% calculate the yields from the degree of poison given.
Precal.Y_eff = (1-Para.deg_poi)*Precal.Yield.C + Para.deg_poi*Precal.Yield.D;
Precal.gamma_eff = (1-Para.deg_poi)*Precal.gamma.C + Para.deg_poi*Precal.gamma.D;

%% sovler settings
% solution output time vector

% FIXME
if ~isfield(IP,'solverTime')
    %error("No solver time supplied");
    warning("No solver time supplied. Using default solver time (0:1:120us).");
    solver.time = ( 0 : 1: 160 ) * 1e-6;  % solution output time vector (start, interval, end) (in mu s)
else
    solver.time = IP.solverTime;
end

solver.timer = (0:10:solver.time(end)*1e6); % a vector that is used for time in the solver
solver.IC = [Spe.ID; T_e0]; % intial condition that will be input in the solver

% sovler options
solver.RelTol = odeset('RelTol',1e-3); % relative tolarance of the solver
%the lower, the slower the code but numerically more accurate; vice versa.
solver.opts = solver.RelTol;
% solver.opts = odeset(solver.opts, ...
%     'Stats', 'on' ...
%     );
% solver.opts = odeset(solver.opts, ...
%     'NonNegative', 1:length(solver.IC)...
%     );

% pack into struct
In = struct( ...
    'Rea', Rea, ...
    'mode', mode, ...
    'IP', IP, ...
    'disch', disch, ...
    'Spe', Spe, ...
    'Range', Range, ...
    'Para', Para, ...
    'Precal', Precal, ...
    'solver', solver ...
    );

%% saving % NOTE : this eats a lot of time
if ~exist('save_input','var') || save_input
    save(fullfile(dir_save,'Input'), '-struct', 'In'); % the workspace containing all input variables are saved to this file
end

end