function [reactions_table] = filterReactions(reactions_table, can_only_contain, must_contain)
%MATERIAL.UTIL.FILTERREACTIONS only keep reactions that contain the specified species
    mask = cellfun(...
        @(reacts) all(ismember(reacts, can_only_contain)) ...
               && any(ismember(reacts, must_contain)), ...
        reactions_table.reactants) ...
         & cellfun(...
        @(reacts) all(ismember(reacts, can_only_contain)) ...
               && any(ismember(reacts, must_contain)), ...
        reactions_table.products);
    reactions_table = reactions_table(mask,:);
end
