function [reactions_table] = reactions()
%SPECIES generate table of nitrogen species reactions
% =========================================================================
% Generate a table containing relevant nitrogen species reactions.
% =========================================================================

%% NOTES: -----------------------------------------------------------------
% TODO : check if it would make sense to give the reactions unique names
% -------------------------------------------------------------------------

%% Reactions table --------------------------------------------------------
var_names       = {'name'       ,'reactants'    ,'products'         ,'eq_type'  ,'coeffs'                               ,'type' ,'source'};

%% Electron Impact Reactions

% Atomic
% >> Ionisation from grd state --------------------------------------------
grd_ion         = {'izcN'       ,{'e','NS'}     ,{'Ni','e','e'}     ,NaN ,[],'ion' ,'';...
                   'izhN'       ,{'eh','NS'}    ,{'Ni','eh','e'}    ,NaN ,[],'ion' ,''};
% >> Ionisation from ionised state ----------------------------------------
% -none-
% >> Ionisation from metastable state -------------------------------------
meta_ion        = {'izcND'      ,{'e','ND'}     ,{'Ni','e','e'}     ,NaN ,[],'ion' ,'';...
                   'izhND'      ,{'eh','ND'}    ,{'Ni','eh','e'}    ,NaN ,[],'ion' ,'';...
                   'izcNP'      ,{'e','NP'}     ,{'Ni','e','e'}     ,NaN ,[],'ion' ,'';...
                   'izhNP'      ,{'eh','NP'}    ,{'Ni','eh','e'}    ,NaN ,[],'ion' ,''};
% >> Excitation from grd state --------------------------------------------
grd_meta        = {'excN'       ,{'e','NS'}     ,{'ND','e'}         ,NaN ,[],'exc' ,'';...
                   'exhN'       ,{'eh','NS'}    ,{'ND','eh'}        ,NaN ,[],'exc' ,'';...
                   'excN'       ,{'e','NS'}     ,{'NP','e'}         ,NaN ,[],'exc' ,'';...
                   'exhN'       ,{'eh','NS'}    ,{'NP','eh'}        ,NaN ,[],'exc' ,''};
% >> Excitation from metastable state -------------------------------------
meta_meta       = {'excND'      ,{'e','ND'}     ,{'NP','e'}         ,NaN ,[],'exc' ,'';...
                   'exhND'      ,{'eh','ND'}    ,{'NP','eh'}        ,NaN ,[],'exc' ,''};
% >> Deexcitation ---------------------------------------------------------
meta_grd        = {'deexcND'    ,{'e','ND'}     ,{'NS','e'}         ,NaN ,[],'exc' ,'';...
                   'deexhND'    ,{'eh','ND'}    ,{'NS','eh'}        ,NaN ,[],'exc' ,'';...
                   'deexcNP'    ,{'e','NP'}     ,{'NS','e'}         ,NaN ,[],'exc' ,'';...
                   'deexhNP'    ,{'eh','NP'}    ,{'NS','eh'}        ,NaN ,[],'exc' ,''};

% Molecular
% >> Ionisation from grd state --------------------------------------------
grd_ion         = {'izcN2'      ,{'e','N2'}     ,{'N2i','e','e'}    ,NaN ,[],'ion' ,'';...
                   'izhN2'      ,{'eh','N2'}    ,{'N2i','eh','e'}   ,NaN ,[],'ion' ,''};
% >> Ionisation from ionised state ----------------------------------------
% -none-
% >> Ionisation from metastable state -------------------------------------
meta_ion        = {'izcN2A'     ,{'e','N2A'}    ,{'N2i','e','e'}    ,NaN ,[],'ion' ,'';...
                   'izhN2A'     ,{'eh','N2A'}   ,{'N2i','eh','e'}   ,NaN ,[],'ion' ,''};
% >> Excitation from grd state --------------------------------------------
grd_meta        = {'excN2'      ,{'e','N2'}     ,{'N2A','e'}        ,NaN ,[],'exc' ,'';...
                   'exhN2'      ,{'eh','N2'}    ,{'N2A','eh'}       ,NaN ,[],'exc' ,''};
% >> Excitation from metastable state -------------------------------------
% -none-
% >> Deexcitation ---------------------------------------------------------
meta_grd        = {'deexcN2A'   ,{'e','N2A'}     ,{'N2','e'}        ,NaN ,[],'deexc' ,'';...
                   'deexhN2A'   ,{'eh','N2A'}    ,{'N2','eh'}       ,NaN ,[],'deexc' ,''};

% Mixed (Dissociation/Recombination)
% >> from grd state
grd_disc        = {'discN2'     ,{'e','N2'}     ,{'NS','NS','e'}    ,NaN ,[],'dis' ,'';...
                   'dishN2'     ,{'eh','N2'}    ,{'NS','NS','eh'}   ,NaN ,[],'dis' ,'';...
                   'discN2'     ,{'e','N2'}     ,{'NS','ND','e'}    ,NaN ,[],'dis' ,'';...
                   'dishN2'     ,{'eh','N2'}    ,{'NS','ND','eh'}   ,NaN ,[],'dis' ,'';...
                   'discN2'     ,{'e','N2'}     ,{'NS','NP','e'}    ,NaN ,[],'dis' ,'';...
                   'dishN2'     ,{'eh','N2'}    ,{'NS','NP','eh'}   ,NaN ,[],'dis' ,'';...
                   'discN2'     ,{'e','N2'}     ,{'NS','Ni','e','e'},NaN ,[],'ion' ,'';...
                   'dishN2'     ,{'eh','N2'}    ,{'NS','Ni','eh','e'},NaN ,[],'ion' ,'';...
                   'discN2'     ,{'e','N2'}     ,{'ND','ND','e'}    ,NaN ,[],'dis' ,'';...
                   'dishN2'     ,{'eh','N2'}    ,{'ND','ND','eh'}   ,NaN ,[],'dis' ,'';...
                   'discN2'     ,{'e','N2'}     ,{'ND','NP','e'}    ,NaN ,[],'dis' ,'';...
                   'dishN2'     ,{'eh','N2'}    ,{'ND','NP','eh'}   ,NaN ,[],'dis' ,'';...
                   'discN2'     ,{'e','N2'}     ,{'ND','Ni','e','e'},NaN ,[],'ion' ,'';...
                   'dishN2'     ,{'eh','N2'}    ,{'ND','Ni','eh','e'},NaN ,[],'ion' ,'';...
                   'discN2'     ,{'e','N2'}     ,{'NP','NP','e'}    ,NaN ,[],'dis' ,'';...
                   'dishN2'     ,{'eh','N2'}    ,{'NP','NP','eh'}   ,NaN ,[],'dis' ,'';...
                   'discN2'     ,{'e','N2'}     ,{'NP','Ni','e','e'},NaN ,[],'ion' ,'';...
                   'dishN2'     ,{'eh','N2'}    ,{'NP','Ni','eh','e'},NaN ,[],'ion' ,''};
% >> from metastable state
meta_disc       = {'discN2A'    ,{'e','N2A'}     ,{'NS','NS','e'}    ,NaN ,[],'dis' ,'';...
                   'dishN2A'    ,{'eh','N2A'}    ,{'NS','NS','eh'}   ,NaN ,[],'dis' ,'';...
                   'discN2A'    ,{'e','N2A'}     ,{'NS','ND','e'}    ,NaN ,[],'dis' ,'';...
                   'dishN2A'    ,{'eh','N2A'}    ,{'NS','ND','eh'}   ,NaN ,[],'dis' ,'';...
                   'discN2A'    ,{'e','N2A'}     ,{'NS','NP','e'}    ,NaN ,[],'dis' ,'';...
                   'dishN2A'    ,{'eh','N2A'}    ,{'NS','NP','eh'}   ,NaN ,[],'dis' ,'';...
                   'discN2A'    ,{'e','N2A'}     ,{'NS','Ni','e','e'},NaN ,[],'ion' ,'';...
                   'dishN2A'    ,{'eh','N2A'}    ,{'NS','Ni','eh','e'},NaN ,[],'ion' ,'';...
                   'discN2A'    ,{'e','N2A'}     ,{'ND','ND','e'}    ,NaN ,[],'dis' ,'';...
                   'dishN2A'    ,{'eh','N2A'}    ,{'ND','ND','eh'}   ,NaN ,[],'dis' ,'';...
                   'discN2A'    ,{'e','N2A'}     ,{'ND','NP','e'}    ,NaN ,[],'dis' ,'';...
                   'dishN2A'    ,{'eh','N2A'}    ,{'ND','NP','eh'}   ,NaN ,[],'dis' ,'';...
                   'discN2A'    ,{'e','N2A'}     ,{'ND','Ni','e','e'},NaN ,[],'ion' ,'';...
                   'dishN2A'    ,{'eh','N2A'}    ,{'ND','Ni','eh','e'},NaN ,[],'ion' ,'';...
                   'discN2A'    ,{'e','N2A'}     ,{'NP','NP','e'}    ,NaN ,[],'dis' ,'';...
                   'dishN2A'    ,{'eh','N2A'}    ,{'NP','NP','eh'}   ,NaN ,[],'dis' ,'';...
                   'discN2A'    ,{'e','N2A'}     ,{'NP','Ni','e','e'},NaN ,[],'ion' ,'';...
                   'dishN2A'    ,{'eh','N2A'}    ,{'NP','Ni','eh','e'},NaN ,[],'ion' ,''};
% >> from ionised state
ion_disc        = {'discN2i'    ,{'e','N2i'}     ,{'NS','NS'}       ,NaN ,[],'dis' ,'';...
                   'discN2i'    ,{'e','N2i'}     ,{'NS','ND'}       ,NaN ,[],'dis' ,'';...
                   'discN2i'    ,{'e','N2i'}     ,{'NS','NP'}       ,NaN ,[],'dis' ,'';...
                   'discN2i'    ,{'e','N2i'}     ,{'NS','Ni','e'}   ,NaN ,[],'ion' ,'';...
                   'dishN2i'    ,{'eh','N2i'}    ,{'NS','Ni','eh'}  ,NaN ,[],'ion' ,'';...
                   'discN2i'    ,{'e','N2i'}     ,{'ND','ND'}       ,NaN ,[],'dis' ,'';...
                   'discN2i'    ,{'e','N2i'}     ,{'ND','NP'}       ,NaN ,[],'dis' ,'';...
                   'discN2i'    ,{'e','N2i'}     ,{'ND','Ni','e'}   ,NaN ,[],'ion' ,'';...
                   'discN2i'    ,{'e','N2i'}     ,{'NP','NP','e'}   ,NaN ,[],'dis' ,'';...
                   'discN2i'    ,{'e','N2i'}     ,{'NP','Ni','e'}   ,NaN ,[],'ion' ,'';...
                   'dishN2i'    ,{'eh','N2i'}    ,{'NP','Ni','eh'}  ,NaN ,[],'ion' ,''};

%% Gas Species Collisions

reactions_cell = [grd_ion; ion_ion; meta_ion; grd_meta; meta_grd];
reactions_table = cell2table(reactions_cell, 'VariableNames', var_names);
end

